// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpkkuxicbtvbwloetyly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwa2t1eGljYnR2Yndsb2V0eWx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTM3OTQsImV4cCI6MjA3MTk2OTc5NH0.cJdMqmfLVp8-9TvfFNEh_nOORnjLlOXPXGHP5bcuSuA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});